vich_uploader:
    db_driver: orm

    mappings:
       listes:
           uri_prefix: /images/listes
           upload_destination: '%kernel.project_dir%/public/images/listes'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
